/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AhorcadosJuego;

import java.util.Random;


/**
 *
 * @author dell
 */
public class Menu extends javax.swing.JFrame {

    private String palabrasecreta = null;

    public Menu() {

        initComponents();
        AdminPalabrasSecretas pals = new AdminPalabrasSecretas();
        JuegoAhorcadoAzar azar = new JuegoAhorcadoAzar(AdminPalabrasSecretas.palabrasSecretas);
        this.setLocationRelativeTo(null);

    }
   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        AhorcadoFijo = new javax.swing.JButton();
        JugarAhorcadoAlAzar = new javax.swing.JButton();
        InicializarPalabras = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        AñadirPalabrasAzar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AhorcadoFijo.setBorder(null);
        AhorcadoFijo.setContentAreaFilled(false);
        AhorcadoFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AhorcadoFijoActionPerformed(evt);
            }
        });
        getContentPane().add(AhorcadoFijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 140, 30));

        JugarAhorcadoAlAzar.setBorder(null);
        JugarAhorcadoAlAzar.setContentAreaFilled(false);
        JugarAhorcadoAlAzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugarAhorcadoAlAzarActionPerformed(evt);
            }
        });
        getContentPane().add(JugarAhorcadoAlAzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 250, 160, 30));

        InicializarPalabras.setBorder(null);
        InicializarPalabras.setContentAreaFilled(false);
        InicializarPalabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicializarPalabrasActionPerformed(evt);
            }
        });
        getContentPane().add(InicializarPalabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 180, 30));

        salir.setBorder(null);
        salir.setContentAreaFilled(false);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, 110, 20));

        AñadirPalabrasAzar.setBorder(null);
        AñadirPalabrasAzar.setContentAreaFilled(false);
        AñadirPalabrasAzar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirPalabrasAzarActionPerformed(evt);
            }
        });
        getContentPane().add(AñadirPalabrasAzar, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 303, 210, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AhorcadosJuego/BG_Ahorcados (2).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AhorcadoFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AhorcadoFijoActionPerformed

        if (palabrasecreta == null) {
            palabrasecreta = "MIAU";
        } else {
            
            if (InicializarPalabrasFijo.palabraDef != null) {
                palabrasecreta = InicializarPalabrasFijo.palabraDef;
            } else {
                System.out.println("Algo esta mal.");
            }
        }
        
        
        
        if (palabrasecreta != null) {
            JuegoAhorcadoFijo juegoAhorcadoFijo = new JuegoAhorcadoFijo(InicializarPalabrasFijo.palabraDef);
            juegoAhorcadoFijo.jugar();

            System.out.println(AdminPalabrasSecretas.getpalabrasSecretas());
        }
        
    }//GEN-LAST:event_AhorcadoFijoActionPerformed

    private void InicializarPalabrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicializarPalabrasActionPerformed
        InicializarPalabrasFijo inicializar = new InicializarPalabrasFijo();
        inicializar.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_InicializarPalabrasActionPerformed

    private void JugarAhorcadoAlAzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugarAhorcadoAlAzarActionPerformed

        Random randy = new Random();
        int aleatorio = randy.nextInt(AdminPalabrasSecretas.palabrasSecretas.size());
        JuegoAhorcadoAzar AhorcadoFijoJuego = new JuegoAhorcadoAzar(AdminPalabrasSecretas.palabrasSecretas);
        AhorcadoFijoJuego.jugar();
        System.out.println(AdminPalabrasSecretas.palabrasSecretas.size());
        System.out.println(aleatorio);

    }//GEN-LAST:event_JugarAhorcadoAlAzarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.out.println("BYE BYEEEEE");
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void AñadirPalabrasAzarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirPalabrasAzarActionPerformed
        AgregarPalabras agregarPalabras = new AgregarPalabras();
        agregarPalabras.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AñadirPalabrasAzarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AhorcadoFijo;
    private javax.swing.JButton AñadirPalabrasAzar;
    private javax.swing.JButton InicializarPalabras;
    private javax.swing.JButton JugarAhorcadoAlAzar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
